
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/team01-f24-03
owner: ucsb-cs156-f24
repo_name: team01-f24-03
pull_requests: [{"author":{"id":"U_kgDOBt2F9Q","is_bot":false,"login":"bsaiju","name":""},"headRefName":"Bharat-HelpRequest-Create-Controller-Get-Post","number":62,"title":"Bharat HelpRequest Controllers","url":"https://github.com/ucsb-cs156-f24/team01-f24-03/pull/62"},{"author":{"id":"U_kgDOBtg9vg","is_bot":false,"login":"eugeneLim628","name":""},"headRefName":"Eugene-UCSBOrgTable","number":55,"title":"Eugene UCSBOrg table ","url":"https://github.com/ucsb-cs156-f24/team01-f24-03/pull/55"}]
