
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/team01-f24-03
owner: ucsb-cs156-f24
repo_name: team01-f24-03
pull_requests: [{"author":{"id":"U_kgDOBs6HEA","is_bot":false,"login":"chloecweng","name":""},"headRefName":"cw-MenuItem-delete","number":54,"title":"UCSBDiningCommonsMenuItem DELETE","url":"https://github.com/ucsb-cs156-f24/team01-f24-03/pull/54"},{"author":{"id":"U_kgDOBs6HEA","is_bot":false,"login":"chloecweng","name":""},"headRefName":"cw-MenuItem-put","number":53,"title":"UCSBDiningCommonsMenuItem PUT","url":"https://github.com/ucsb-cs156-f24/team01-f24-03/pull/53"},{"author":{"id":"U_kgDOBs6HEA","is_bot":false,"login":"chloecweng","name":""},"headRefName":"cw-MenuItem-get","number":52,"title":"UCSBDiningCommonsMenuItem GET","url":"https://github.com/ucsb-cs156-f24/team01-f24-03/pull/52"},{"author":{"id":"U_kgDOBs6HEA","is_bot":false,"login":"chloecweng","name":""},"headRefName":"cw-UCSBDiningCommonsMenuItem-controller","number":51,"title":"UCSBDiningCommonsMenuItem Controller","url":"https://github.com/ucsb-cs156-f24/team01-f24-03/pull/51"},{"author":{"id":"U_kgDOBtzY9A","is_bot":false,"login":"pballani","name":""},"headRefName":"Priyanka-RecReqTable","number":48,"title":"Created database table for RecommendationRequest","url":"https://github.com/ucsb-cs156-f24/team01-f24-03/pull/48"}]
